export default {
  'icon-chart': 'icon-flyfish-line',
  'icon-media': 'icon-flyfish-pic',
  'icon-layout': 'icon-flyfish-ai234',
  'icon-text': 'icon-flyfish-text',
  'icon-widget': 'icon-flyfish-other',
  'icon-pictorial-chart': 'icon-flyfish-xiangxingtu',
  'icon-progress-bar': 'icon-flyfish-jindutiao',
  'icon-bar-chart': 'icon-flyfish-bingtu',
  'icon-radar-chart': 'icon-flyfish-leidatu',
  'icon-gauge-chart': 'icon-flyfish-yibiaopan',
  'icon-contain-box': 'icon-flyfish-rongqikuang',
  'icon-button': 'icon-flyfish-button',
  'icon-navigation': 'icon-flyfish-daohanglan',
  'icon-scatter-chart': 'icon-flyfish-sandiantu',
  'icon-title': 'icon-flyfish-text1',
  'icon-map': 'icon-flyfish-map',
  'icon-table': 'icon-flyfish-table',
  'icon-water-wave-chart': 'icon-flyfish-shuiboqiu',
  'icon-number-show': 'icon-flyfish-shuzizhanshi',
  'icon-flow-arrow': 'icon-flyfish-liudongjiant',
};
